# local-dev에 필요한 postgresql을 docker로 실행하기 위한 파일
version: "3.8"

volumes:
  postgres-data-volumn:

services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    restart: always
    volumes:
      - postgres-data-volumn:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
