name: Pylint

on:
  push:
    paths:
      - "app/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip poetry
      # ----------------------
      - name: Activate virtualenv
        run: |
          poetry export -f requirements.txt --output requirements.txt --with dev
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      # ----------------------------
      - name: Analysing the code with pylint
        run: |
          python -m pylint app
