name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.5.0"
      - name: Install dependencies
        run: |
          poetry install
      - name: Analysing the code with pylint
        run: |
          poetry shell && pylint app
