name: Ruff

on:
  push:
    branches:
      - main
    paths:
      - "app/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8
        with:
            poetry-version: "1.5.0"
      - uses: chartboost/ruff-action@v1
